### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by adius** [jywarren/image-sequencer#2]
I was looking the whole day for an app like this.
I thought somebody must have already build a sequential image processing library and I guess I was right =D
Can't wait to see where this is going =)

**Comment by adius** [comment]
(As you might have guessed this is not an issue so feel free to close it =D)

**Comment by adius** [comment]
Let me know if I can help you somehow!

**Comment by jywarren** [comment]
:-) thanks, @adius -- still haven't finalized things or published a release, as I'm talking with a few other folks to try to get an initial module-level API designed. One which can cover a range of possible use cases (explained in the README at the bottom, for now).

What brings you to the repository?

**Comment by adius** [comment]
OK, I will stay tuned.

I was dreaming of an image processing app which works completely non-destructive and where I can change each processing step afterwards.
https://github.com/imgflo/imgflo has been the closest to my vision so far.

It's really funny, I literally have an idea note which describes an app like image-sequencer.
I was going to call it "PipeEdit" as you pipe the output of one filter into the next filter.

My usecase would for example be:
image |  black & white | remove speckles | perspective transformation | crop  | save

Then you could easily change the black & white threshold and still see the final output

**Comment by jywarren** [comment]
yay awesome, this has been sort of brewing in my mind for some time, and i just started coding it up. I think one of the keys will be the exact module API, so that it's very easy to contribute to. 

Thanks for the links on imgflo -- added some things to the README based on it.

**Comment by jywarren** [comment]
There'll be a separation between UI and function, so I imagine a node-and-line based UI like https://github.com/flowhub/the-graph could be an alternative way to sequence modules.

**Comment by adius** [comment]
> i just started coding it up
I wish I had the time 🙈

> I imagine a node-and-line based UI like https://github.com/flowhub/the-graph

Although the project is quite cool, I'm not a fan of graph/node based UIs anymore.
I always feel like I'm spending more time on rearranging the nodes than really working 😅.
I think for image processing a linear flow like you already started building is much better.
You'll always start with an image or an empty canvas and add and modify the content step by step.
Maybe addition content can come from both sides, but you'll always have one main processing line.

**Comment by jywarren** [comment]
This is really getting there, slowly I admit -- API is basically stable now, but starting to work with `node-canvas` for headless testing, and not all upstream modules support that.

Also, moving the root over here: https://github.com/publiclab/image-sequencer/

And will close out issues here soon. Thanks!
