### ISSUE TITLE
Adding dist directory to .gitignore

### ISSUE THREAD

**Issue by djmgit** [jywarren/image-sequencer#3]
Tracking the dist directory is unnecessary as after cloning the repo `grunt build` can be used to build the source.More over when applying git diff, seeing difference in dist files is of not much use as changes made in the src directory files are of much more concern.

**Comment by jywarren** [comment]
well, the dist directory is important because we publish it on npmjs.org, and people can also use NPM or bower to directly include that file from our repository. 

I'm going to close this, but thank you for thinking about this!
