### ISSUE TITLE
Demos do not run (Safari,Firefox)

### ISSUE THREAD

**Issue by ccpandhare** [jywarren/image-sequencer#5]
I was trying to run the demos (from the links in the Readme.md).
getPixels caused CORS Error on Safari
the console shows 'Bad Image Path' for each step on Firefox

Error Data:
getPixels — image-sequencer.js:15819 Cross-origin image load denied by Cross-Origin Resource Sharing policy.

**Comment by jywarren** [comment]
Thank you! Did they run for you on chrome? This was the GitHub hosted
demos, right? And these errors happened when you dragged in an image?

Working on a new release!

**Comment by ccpandhare** [comment]
No, they didn't work on Chrome. (Chrome on Mac behaves just like Safari for some reason.)
Yes the GitHub demos.
These errors occurred when i selected an image.

I'll try to work on this and fix it. Any other tasks which I can do?

I'd like to contribute to Image Sequencer in GSoC 2017.

**Comment by jywarren** [comment]
Hi, the latest release hasn't been pushed out for the Github Pages demos, which run on the `gh-pages` branch, only for the master branch. I'll fix that now, can you check again in these browsers?

**Comment by jywarren** [comment]
OK, the `gh-pages` demos are now updated. Can you try again?
