### ISSUE TITLE
Demo gives out Error

### ISSUE THREAD

**Issue by ccpandhare** [jywarren/image-sequencer#6]
After the latest commit,
Demo page gives an error every time an additional module is loaded (after the initial NDVI and Colorbar)

[Error] TypeError: undefined is not an object (evaluating 'options.el.html')
	draw (image-sequencer.js:184409)
	run (image-sequencer.js:184221)
	(anonymous function) (index.html:76)
	dispatch (image-sequencer.js:60435)
	handle (image-sequencer.js:60247)

**Comment by jywarren** [comment]
Hi, are you running it locally? 

I just confirmed that the demo at `/index.html` it runs on latest Chrome -- or are you running `/examples/ndvi/index.html`? The NDVI demo seems to take a very long time for me, but I don't see a specific error as you cite.

**Comment by jywarren** [comment]
OK, the `gh-pages` demos are now updated. Can you try again?

**Comment by jywarren** [comment]
I'm also moving things to https://github.com/publiclab/image-sequencer/ -- will soon shut down issues over here, thanks!

**Comment by ccpandhare** [comment]
Yes, I have been running /examples/ndvi/index.html

Sorry,
I still get the same error (Safari on Mac)
I get another error (Firefox on Mac)
ReferenceError: event is not defined  image-sequencer.js:184383:11
	onImage/reader.onload /dist/image-sequencer.js:184383:11

Since you're shutting down issues here, Is it okay if I reopen these issues on the publiclab repo?

Added an issue on the publiclab repo

Thanks!

**Comment by jywarren** [comment]
Yes please do re-open over there. Closing here!
